export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'

export const ROOMS_LOADING_SUCCESS = 'ROOM_LOADING_SUCCESS'
export const CHATS_LOADING_SUCCESS = 'CHAT_LOADING_SUCCESS'

export const ROOM_SELECTED = 'ROOM_SELECTED'
